import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navigation/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Algorithm Visualizer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='overflow-y-hidden'>
      <body className={inter.className + ` overflow-y-hidden`}>
          <Navbar />
          <main className="min-h-screen bg-stone-100">
            {children}
          </main>
        </body>
    </html>
  )
}
